// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoafmsmlkqzumiolplwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYWZtc21sa3F6dW1pb2xwbHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTE0OTAsImV4cCI6MjA2NTE2NzQ5MH0.n0vd3bY2Dy60x9neGH5DYBrkOnPOYE7iYvMjBQcaEAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});